qca-swiss-army-knife: Add perl and python to rdeps
Addresses
ERROR: QA Issue: /usr/bin/ath10k-bdencoder contained in package qca-swiss-army-knife requires /usr/bin/python3, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]
ERROR: QA Issue: /usr/bin/read-powers contained in package qca-swiss-army-knife requires /usr/bin/python, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]
ERROR: QA Issue: /usr/bin/irq-watch contained in package qca-swiss-army-knife requires /usr/bin/perl, but no providers found in RDEPENDS_qca-swiss-army-knife? [file-rdeps]

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 0622a3f239efc91b055ce0a25d950346fddf2532)