qdl: needs pkgconfig and udev
Fixes build issues e.g.
| qdl.c:43:10: fatal error: 'libudev.h' file not found
| #include <libudev.h>
|          ^~~~~~~~~~~

/bin/sh: pkg-config: command not found
patch.c:33:10: fatal error: libxml/parser.h: No such file or directory
   33 | #include <libxml/parser.h>
      |          ^~~~~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>
(cherry picked from commit 7ce246b155ce991f3e084eec4cd46a94e790e985)